networks:
  network2:
    name: network2
services:
  nginx2:
    container_name: nginx2
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    networks:
      - network2
    depends_on:
      - php2
      - mysql2
  php2:
    container_name: php2
    build: ./images/php
    volumes:
      - ./www:/var/www/html
    networks:
      - network2
    depends_on: 
      - mysql2
  mysql2:
    container_name: mysql2
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network2
  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql2  
    networks:
      - network2  
    depends_on:
      - mysql2